language: cpp

os: linux
dist: xenial
sudo: true
compiler: gcc

before_install:
  - sudo apt-get install -y  libtinyxml2-dev libcurl4-openssl-dev libarmadillo-dev libgazebo-dev
  - wget https://github.com/Dronecode/DronecodeSDK/releases/download/v0.14.2/libdronecode-sdk-dev_0.14.2_ubuntu16.04_amd64.deb
  - sudo dpkg -i libdronecode-sdk-dev_0.14.2_ubuntu16.04_amd64.deb
  addons:
  apt:
    update: true

install:
- set -e
- mkdir build
- cd build
- cmake ../
- make 

   
