// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResetModel.proto

#include "ResetModel.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace reset_model_msg {
namespace msg {
constexpr ResetModel::ResetModel(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : reset_(false){}
struct ResetModelDefaultTypeInternal {
  constexpr ResetModelDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ResetModelDefaultTypeInternal() {}
  union {
    ResetModel _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ResetModelDefaultTypeInternal _ResetModel_default_instance_;
}  // namespace msg
}  // namespace reset_model_msg
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ResetModel_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ResetModel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ResetModel_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ResetModel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::reset_model_msg::msg::ResetModel, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::reset_model_msg::msg::ResetModel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::reset_model_msg::msg::ResetModel, reset_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::reset_model_msg::msg::ResetModel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::reset_model_msg::msg::_ResetModel_default_instance_),
};

const char descriptor_table_protodef_ResetModel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020ResetModel.proto\022\023reset_model_msg.msg\""
  "\033\n\nResetModel\022\r\n\005reset\030\001 \002(\010"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ResetModel_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ResetModel_2eproto = {
  false, false, 68, descriptor_table_protodef_ResetModel_2eproto, "ResetModel.proto", 
  &descriptor_table_ResetModel_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_ResetModel_2eproto::offsets,
  file_level_metadata_ResetModel_2eproto, file_level_enum_descriptors_ResetModel_2eproto, file_level_service_descriptors_ResetModel_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_ResetModel_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ResetModel_2eproto);
  return descriptor_table_ResetModel_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ResetModel_2eproto(&descriptor_table_ResetModel_2eproto);
namespace reset_model_msg {
namespace msg {

// ===================================================================

class ResetModel::_Internal {
 public:
  using HasBits = decltype(std::declval<ResetModel>()._has_bits_);
  static void set_has_reset(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

ResetModel::ResetModel(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:reset_model_msg.msg.ResetModel)
}
ResetModel::ResetModel(const ResetModel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  reset_ = from.reset_;
  // @@protoc_insertion_point(copy_constructor:reset_model_msg.msg.ResetModel)
}

void ResetModel::SharedCtor() {
reset_ = false;
}

ResetModel::~ResetModel() {
  // @@protoc_insertion_point(destructor:reset_model_msg.msg.ResetModel)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ResetModel::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ResetModel::ArenaDtor(void* object) {
  ResetModel* _this = reinterpret_cast< ResetModel* >(object);
  (void)_this;
}
void ResetModel::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ResetModel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ResetModel::Clear() {
// @@protoc_insertion_point(message_clear_start:reset_model_msg.msg.ResetModel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reset_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResetModel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required bool reset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reset(&has_bits);
          reset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResetModel::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:reset_model_msg.msg.ResetModel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required bool reset = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_reset(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:reset_model_msg.msg.ResetModel)
  return target;
}

size_t ResetModel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:reset_model_msg.msg.ResetModel)
  size_t total_size = 0;

  // required bool reset = 1;
  if (_internal_has_reset()) {
    total_size += 1 + 1;
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResetModel::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:reset_model_msg.msg.ResetModel)
  GOOGLE_DCHECK_NE(&from, this);
  const ResetModel* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResetModel>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:reset_model_msg.msg.ResetModel)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:reset_model_msg.msg.ResetModel)
    MergeFrom(*source);
  }
}

void ResetModel::MergeFrom(const ResetModel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:reset_model_msg.msg.ResetModel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_reset()) {
    _internal_set_reset(from._internal_reset());
  }
}

void ResetModel::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:reset_model_msg.msg.ResetModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResetModel::CopyFrom(const ResetModel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:reset_model_msg.msg.ResetModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResetModel::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void ResetModel::InternalSwap(ResetModel* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(reset_, other->reset_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResetModel::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace reset_model_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::reset_model_msg::msg::ResetModel* Arena::CreateMaybeMessage< ::reset_model_msg::msg::ResetModel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::reset_model_msg::msg::ResetModel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
