from numpy import genfromtxt
import textwrap 
import argparse
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sys

"""
Error files need to be formated as one column file
This column contain the mean error of each flight

"""

def plot_flight_error(error_file_name):
    num_lines = sum(1 for line in open(error_file_name))
    print (num_lines)
    
    y = np.loadtxt(error_file_name)
    x = np.arange(y.size)
    
    print(y)
    
    z = np.mean(y)
    
    print ("error standard deviation : ", np.std(y))    
    print(z)
    #plt.ylim(-1, +9)
    
    plt.plot(x, y, color='blue')
    
    plt.xlabel('Number of flight')
    plt.ylabel('Error of deformation combined totatly in m')

    figure = plt.gcf() # get current figure
    figure.set_size_inches(25, 6)    
    
    plt.savefig(error_file_name + ".png", dpi=100)
    

"""
Count files need to be formated as one column file
This column contain the number of steps of each flight
"""

def plot_flight_count(count_file_name):
    
    num_lines = sum(1 for line in open(count_file_name))
    print (num_lines)
    
    y = np.loadtxt(count_file_name)
    x = np.arange(y.size)    
    z = np.mean(y)
    
    print ("count deviation: ", np.std(y) )
    print(z)
    
    plt.plot(x, y, color='blue')
    
    plt.xlabel('Number of flights')
    plt.ylabel('Controller Counts before deformation')
    
    figure = plt.gcf() # get current figure
    figure.set_size_inches(25, 6)    

    plt.savefig(count_file_name + ".png", dpi=100)


def plot_histogram(count_file_name, histogram_file_name):
    x = np.loadtxt(count_file_name)
    plt.hist(x, bins=3)

    plt.xlabel('Number of time steps')
    plt.ylabel('Frequency')
    
    figure = plt.gcf() 
    figure.set_size_inches(25, 6)    

    plt.savefig(histogram_file_name + ".png", dpi=100)

    
def plot_histogram_2d(histogram_file_name):
    
    data = pd.read_csv(histogram_file_name, sep=' ',header=None, index_col =0)

    data.plot(kind='bar')
    plt.xlabel('Number of time steps')
    plt.ylabel('Frequency')
            
    figure = plt.gcf() # get current figure
    figure.set_size_inches(25, 6)    

    plt.savefig(histogram_file_name + ".png", dpi=100)

    
if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        prog='Plotting script',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent('''\
        PLotting script!
        --------------------------------
        This script is used to plot the result generated by the
        quadcopters in the simulator
        It can be used to plot one of the files, 
        or all of them at the same time.
        You have to provide the file format as described in the above comments.
        '''))
    
    parser.add_argument('--error_file_name', metavar="error file name", type=str, help="Enter error file name that has the mean value of each flight")
    parser.add_argument('--count_file_name', metavar="count file name", type=str, help="Enter flight count file name  ")
    parser.add_argument('--histogram_file_name', metavar="histogtam file name", type=str, help="Enter histogram file name, two column file name, nuumber of steps and frequency")
    
    args = parser.parse_args()

    if len(sys.argv)==1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    
    if args.error_file_name:
        plot_flight_error(args.error_file_name)

    elif args.count_file_name:    
        plot_flight_count(args.count_file_name)

    elif args.histogram_file_name:   
        plot_histogram_2d(args.histogram_file_name)


    
